# Generated by Django 4.2.11 on 2024-07-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestselling',
            name='backImg',
            field=models.CharField(help_text='Provide a image link', max_length=300),
        ),
        migrations.AlterField(
            model_name='bestselling',
            name='frontImg',
            field=models.CharField(help_text='Provide a image link', max_length=300),
        ),
    ]
